easy_admin:
   design:
       menu:
           - { label: 'Back to homepage', route: 'home', icon: home }
           - { entity: 'User'}
           - { entity: 'Story'}
           - { entity: 'Topic'}
           - { entity: 'Patronage'}

   list:
      title: 'List of %%entity_label%%'
      actions:
          - { name: edit, icon: pencil-square-o, label: ' '}
          - { name: show, icon: 'info-circle', label: ' '}
          - { name: delete, icon: trash-o, label: ' ' }
   entities:
       User:
           class: App\Entity\User
           label: 'Members'
           list:
               fields:
                   - 'id'
                   - 'fullname'
                   - { property: 'email', type: 'email'}
                   - { property: 'activated', label: 'Activate'}
                   - { property: 'deactivated', label: 'Deactivate', type: toggle }
                   - 'role'
                   - { property: 'registeredOn', format: 'm/d/Y' }
           show:
               fields:
                    - 'id'
                    - 'fullname'
                    - { property: 'email', type: 'email'}
                    - { property: 'activated', label: 'Activate'}
                    - 'role'
                    - { property: 'registeredOn', format: 'm/d/Y' }
               actions:
                    - { name: edit, icon: pencil, label: 'Edit'}
                    - { name: delete, icon: trash-o, label: 'Delete'}
           edit:
               fields:
                   - 'role'
               actions:
               - { name: delete, icon: trash-o, label: 'Delete'}

       Story:
           class: App\Entity\Story
           label: 'Stories'
           list:
               fields:
                   - 'id'
                   - 'title'
                   - 'topicType'
                   - 'author'
                   - 'patronage by'
                   - { property: 'countryName', label: 'Country' }
                   - { property: 'createdOn', format: 'm/d/Y' }
                   - { property: 'validated', type: toggle }
           show:
               fields:
                   - 'title'
                   - { property: 'abstract', type: 'raw' }
                   - { property: 'plot', type: 'raw' }
                   - { property: 'countryName', label: 'Country' }
                   - { property: 'createdOn', format: 'm/d/Y' }
                   - 'author'
                   - 'topicType'
                   - 'patronage by'
               actions:
                   - { name: edit, icon: pencil, label: 'Edit'}
                   - { name: delete, icon: trash-o, label: 'Delete'}
           edit:
               fields:
                   - { property: 'title'}
                   - { property: 'abstract'}
                   - { property: 'plot'}
               actions:
                   - { name: delete, icon: trash-o, label: 'Delete'}

       Topic:
           class: App\Entity\Topic
           label: 'Topics'
           list:
               fields:
                   - 'id'
                   - 'type'
                   - { property: 'stories', label: 'Number of related stories' }
           show:
               fields:
                   - 'id'
                   - 'type'
               actions:
                   - { name: edit, icon: pencil, label: 'Edit'}
                   - { name: delete, icon: trash-o, label: 'Delete'}
           edit:
               fields:
                   - 'type'
               actions:
                   - { name: delete, icon: trash-o, label: 'Delete'}
           new:
               fields:
                   - 'type'
               actions:
                   - { name: delete, icon: trash-o, label: 'Delete'}

       Patronage:
           class: App\Entity\Patronage
           label: 'Patronages'
           list:
               fields:
                   - 'id'
                   - 'organization'
                   - { property: 'stories', label: 'Number of related stories' }
           show:
               fields:
                   - 'id'
                   - 'organization'
               actions:
                   - { name: edit, icon: pencil, label: 'Edit'}
                   - { name: delete, icon: trash-o, label: 'Delete'}
           edit:
               fields:
                   - 'organization'
               actions:
                   - { name: delete, icon: trash-o, label: 'Delete'}
           new:
               fields:
                   - 'organization'
               actions:
                   - { name: delete, icon: trash-o, label: 'Delete'}

   site_name: Climate stories bank
