security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_EDIT: [ROLE_USER]
        ROLE_ADMIN: [ROLE_EDIT]

    providers:
        main:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        main:
            provider: main
            pattern: ^/
            anonymous: true
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: login
            remember_me:
                secret: '%env(SECRET)%'
                lifetime: 259200
                path: /
                httponly: true

    access_control:
        - { path: ^/story, roles: ROLE_USER }
        - { path: ^/story/add-story, roles: ROLE_EDIT }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
