home:
    path: /
    defaults:
         _controller: App\Action\HomeAction

story:
    path: /story/{storyId}
    defaults:
        _controller: App\Action\StoryAction
    requirements:
        storyId: \d+

addStory:
    path: /add-story
    defaults:
       _controller: App\Action\AddStoryAction

register:
    path: /register
    defaults:
        _controller: App\Controller\IndexController::register

login:
    path: /login
    defaults:
        _controller: App\Controller\IndexController::login

login_check:
    path: /login_check

logout:
    path: /logout

lostPassword:
    path: /lost-password
    defaults:
            _controller: App\Controller\IndexController::newPswdMail

resetPswd:
    path: /lost-password/{expireOn}/{email}/{token}
    defaults:
        _controller: App\Controller\IndexController::newPswdProcess
    requirements:
        expireOn: ^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])
        email: ^[a-z0-9._-]+@[a-z0-9._-]{2,}\.[a-z]{2,4}$
        token: ([^']{40,})

validation:
    path: /validation/{expireOn}/{email}/{token}
    defaults:
        _controller: App\Controller\IndexController::activation
    requirements:
        expireOn: ^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])
        email: ^[a-z0-9._-]+@[a-z0-9._-]{2,}\.[a-z]{2,4}$
        token: ([^']{40,})

browse:
    path: /browse-stories/page/{pageNumber}/{worldArea}/{country}/{topic}/{patronage}
    defaults:
        _controller: App\Controller\IndexController::browse
        worldArea: null
        country: null
        topic: null
        patronage: null
    requirements:
        pageNumber: \d+

search:
    path: /search
    defaults:
        _controller: App\Controller\IndexController::search

admin:
    path: /admin
    defaults:
        _controller: App\Action\AdminHomeAction

adminDeleteUnactivated:
    path: /admin/delete-unactivated-account
    defaults:
        _controller: App\Action\AdminDeleteUnactivatedAction


adminUser:
    path: /admin/user
    defaults:
        _controller: App\Action\AdminUserAction


adminByUser:
    path: /admin/user/{id}
    defaults:
        _controller: App\Action\AdminByUserAction
    requirements:
        id: \d+


adminStory:
    path: /admin/story/{filter}/{filterId}
    defaults:
        _controller: App\Action\AdminStoryAction
        filter: null
        filterId: null
    requirements:
        filter: user||worldArea||country||topic||patronage
        filterId: \d+

adminByStory:
    path: /admin/story-informations/{id}
    defaults:
        _controller: App\Action\AdminByStoryAction
    requirements:
        id: \d+

adminEditStory:
    path: /admin/story/edit/{id}
    defaults:
        _controller: App\Action\AdminEditStoryAction
    requirements:
        id: \d+

adminTopic:
    path: /admin/topic
    defaults:
        _controller: App\Action\AdminTopicAction

adminPatronage:
    path: /admin/patronage
    defaults:
        _controller: App\Action\AdminPatronageAction

adminActions:
    path: /admin/{entity}/{id}/{action}
    defaults:
        _controller: App\Action\AdminEntityManagementAction
    requirements:
        entity: story||user
        id: \d+
        action: delete||upgrade||downgrade||validate
