home:
    path: /
    defaults:
         _controller: App\Controller\IndexController::home

story:
    path: /story/{storyId}
    defaults:
        _controller: App\Controller\IndexController::Story
    requirements:
        storyId: \d+

addStory:
    path: /add-story
    defaults:
       _controller: App\Controller\IndexController::addStory

register:
    path: /register
    defaults:
        _controller: App\Controller\IndexController::register

login:
    path: /login
    defaults:
        _controller: App\Controller\IndexController::login

login_check:
    path: /login_check

logout:
    path: /logout

lostPassword:
    path: /lost-password
    defaults:
            _controller: App\Controller\IndexController::newPswdMail

resetPswd:
    path: /lost-password/{expireOn}/{email}/{token}
    defaults:
        _controller: App\Controller\IndexController::newPswdProcess
    requirements:
        expireOn: ^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])
        email: ^[a-z0-9._-]+@[a-z0-9._-]{2,}\.[a-z]{2,4}$
        token: ([^']{40,})

validation:
    path: /validation/{expireOn}/{email}/{token}
    defaults:
        _controller: App\Controller\IndexController::activation
    requirements:
        expireOn: ^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])
        email: ^[a-z0-9._-]+@[a-z0-9._-]{2,}\.[a-z]{2,4}$
        token: ([^']{40,})

browse:
    path: /browse-stories/page/{pageNumber}/{worldArea}/{country}/{topic}/{patronage}
    defaults:
        _controller: App\Controller\IndexController::browse
        worldArea: null
        country: null
        topic: null
        patronage: null
    requirements:
        pageNumber: \d+

search:
    path: /search
    defaults:
        _controller: App\Controller\IndexController::search

admin:
    path: /admin
    defaults:
        _controller: App\Controller\AdminController::adminHome

adminUser:
    path: /admin/user
    defaults:
        _controller: App\Controller\AdminController::adminUser

adminByUser:
    path: /admin/user/{id}
    defaults:
        _controller: App\Controller\AdminController::adminByUser
    requirements:
        id: \d+

adminStory:
    path: /admin/story
    defaults:
        _controller: App\Controller\AdminController::adminStory

adminByStory:
    path: /admin/story/{id}
    defaults:
        _controller: App\Controller\AdminController::adminByStory
    requirements:
        id: \d+

adminEditStory:
    path: /admin/story/edit/{id}
    defaults:
        _controller: App\Controller\AdminController::adminEditStory
    requirements:
        id: \d+

adminTopic:
    path: /admin/topic
    defaults:
        _controller: App\Controller\AdminController::adminTopic

adminPatronage:
    path: /admin/patronage
    defaults:
        _controller: App\Controller\AdminController::adminPatronage

adminActions:
    path: /admin/{entity}/{id}/{action}
    defaults:
        _controller: App\Controller\AdminController::adminEntityManagement
    requirements:
        entity: story||user
        id: \d+
        action: delete||upgrade||downgrade||validate
