home:
    path: /
    defaults:
         _controller: App\Controller\IndexController::home

story:
    path: /story/{storyId}
    defaults:
        _controller: App\Controller\IndexController::Story
    requirements:
        storyId: \d+

addStory:
    path: /add-story
    defaults:
       _controller: App\Controller\IndexController::addStory

resgister:
    path: /register
    defaults:
        _controller: App\Controller\IndexController::register

# first, run composer req annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation
