home:
    path: /
    defaults:
         _controller: App\Action\HomeAction

story:
    path: /story/{storyId}
    defaults:
        _controller: App\Action\StoryAction
    requirements:
        storyId: \d+

addStory:
    path: /add-story
    defaults:
       _controller: App\Action\AddStoryAction

register:
    path: /register
    defaults:
        _controller: App\Action\Security\RegisterAction

login:
    path: /login
    defaults:
        _controller: App\Action\Security\LoginAction

login_check:
    path: /login_check

logout:
    path: /logout

lostPassword:
    path: /lost-password
    defaults:
            _controller: App\Action\LostPasswordAction

resetPswd:
    path: /lost-password/{expireOn}/{email}/{token}
    defaults:
        _controller: App\Action\ResetPswdAction
    requirements:
        expireOn: ^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])
        email: ^[a-z0-9._-]+@[a-z0-9._-]{2,}\.[a-z]{2,4}$
        token: ([^']{40,})

validation:
    path: /validation/{expireOn}/{email}/{token}
    defaults:
        _controller: App\Action\ActivateAction
    requirements:
        expireOn: ^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])
        email: ^[a-z0-9._-]+@[a-z0-9._-]{2,}\.[a-z]{2,4}$
        token: ([^']{40,})

browse:
    path: /browse-stories/page/{pageNumber}/{worldArea}/{country}/{topic}/{patronage}
    defaults:
        _controller: App\Action\BrowseAction
        worldArea: null
        country: null
        topic: null
        patronage: null
    requirements:
        pageNumber: \d+

search:
    path: /search
    defaults:
        _controller: App\Action\SearchAction

admin:
    path: /admin
    defaults:
        _controller: App\Action\Admin\AdminHomeAction

adminDeleteUnactivated:
    path: /admin/delete-unactivated-account
    defaults:
        _controller: App\Action\Admin\AdminDeleteUnactivatedAction


adminUser:
    path: /admin/user
    defaults:
        _controller: App\Action\Admin\AdminUserAction


adminByUser:
    path: /admin/user/{id}
    defaults:
        _controller: App\Action\Admin\AdminByUserAction
    requirements:
        id: \d+


adminStory:
    path: /admin/story/{filter}/{filterId}
    defaults:
        _controller: App\Action\Admin\AdminStoryAction
        filter: null
        filterId: null
    requirements:
        filter: user||worldArea||country||topic||patronage
        filterId: \d+

adminByStory:
    path: /admin/story-informations/{id}
    defaults:
        _controller: App\Action\Admin\AdminByStoryAction
    requirements:
        id: \d+

adminEditStory:
    path: /admin/story/edit/{id}
    defaults:
        _controller: App\Action\Admin\AdminEditStoryAction
    requirements:
        id: \d+

adminTopic:
    path: /admin/topic
    defaults:
        _controller: App\Action\Admin\AdminTopicAction

adminPatronage:
    path: /admin/patronage
    defaults:
        _controller: App\Action\Admin\AdminPatronageAction

adminActions:
    path: /admin/{entity}/{id}/{action}
    defaults:
        _controller: App\Action\Admin\AdminEntityManagementAction
    requirements:
        entity: story||user||term
        id: \d+
        action: delete||upgrade||downgrade||validate||reject

adminLegal:
    path: /admin/legal
    defaults:
        _controller: App\Action\Admin\AdminLegalAction

adminLegalCreate:
    path: /admin/legal/create-legal
    defaults:
        _controller: App\Action\Admin\AdminLegalCreateAction

adminByLegal:
    path: /admin/legal/{id}
    defaults:
        _controller: App\Action\Admin\AdminByLegalAction
    requirements:
        id: \d+

adminEditLegal:
  path: /admin/legal/edit/{id}
  defaults:
      _controller: App\Action\Admin\AdminEditLegalAction
  requirements:
      id: \d+



