App\Entity\Notification:
    type: entity
    table: onu_notification
    repositoryClass: App\Repository\NotificationRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        type:
            type: smallint
            nullable: false
            unique: false
        seen:
            type: boolean
            options:
                default: false
        notifiedOn:
            type: date
            nullable: false
            unique: false
    manyToOne:
        user:
            targetEntity: App\Entity\User
            inversedBy: notifications
            joinColumn:
                name: user_id
                referencedColumnName: id



