App\Entity\Patronage:
    type: entity
    table: patronage
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        organization:
            type: string
            length: 30
            nullable: false
            unique: false
    oneToMany:
        stories:
            targetEntity: App\Entity\Story
            mappedBy: patronage
            cascade: ['persist', 'remove']
