App\Entity\Term:
    type: entity
    table: term
    repositoryClass: App\Repository\TermRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 30
            nullable: false
            unique: true
        article:
            type: text
            nullable: false
        status:
            type: string
            length: 30
            nullable: false
        createdOn:
            type: date
            nullable: false
        publishedOn:
            type: date
            nullable: true
