App\Entity\Topic:
    type: entity
    table: topic
    repositoryClass: App\Repository\TopicRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: 20
            nullable: false
            unique: false
    oneToMany:
        stories:
            targetEntity: App\Entity\Story
            mappedBy: topic
            cascade: ['persist']